#!/bin/bash

# Update packages and install necessary tools
sudo apt update && sudo apt upgrade -y
sudo apt install curl gnupg software-properties-common -y

# Install Blender
# sudo apt install blender -y
sudo apt install snap
sudo snap install blender --classic
 
# Install FFmpeg
sudo apt install ffmpeg -y

# Install Node.js for WebSocket server
sudo apt install nodejs npm -y

# Install Jellyfin
# Enable Universe repository for FFmpeg dependencies
sudo add-apt-repository universe -y

# Import the GPG signing keys for Jellyfin
curl -fsSL [5](https://repo.jellyfin.org/jellyfin_team.gpg.key) | sudo gpg --dearmor -o /etc/apt/keyrings/jellyfin.gpg

# Add Jellyfin repository
export VERSION_OS="$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release )"
export VERSION_CODENAME="$( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release )"
export DPKG_ARCHITECTURE="$( dpkg --print-architecture )"
cat <<EOF | sudo tee /etc/apt/sources.list.d/jellyfin.sources
Types: deb
URIs: [6](https://repo.jellyfin.org/)${VERSION_OS}
Suites: ${VERSION_CODENAME}
Components: main
Architectures: ${DPKG_ARCHITECTURE}
Signed-By: /etc/apt/keyrings/jellyfin.gpg
EOF

# Update packages and install Jellyfin
sudo apt update && sudo apt install jellyfin -y

